[tool.poetry]
name = "asyncalchemy"
version = "0.0.0"   # For poetry-dynamic-versioning
description = "A thin async wrapper for SQLAlchemy sessions."
authors = ["Claroty Open Source <opensource@claroty.com>",
           "Shaul Kramer <shaulkr@gmail.com>",
           "Guy Zylberberg <guyzyl@gmail.com>",
           "Amit Itzkovitch <amit7itz@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/claroty/AsyncAlchemy"
documentation = "https://github.com/claroty/AsyncAlchemy"
exclude = ["asyncalchemy/tests"]


[tool.poetry.dependencies]
python = "^3.6"
sqlalchemy = "^1.2.0"


[tool.poetry.dev-dependencies]
mypy = "^0.790"
pylint = "^2.6"
pytest = "^6.2.1"
pytest-asyncio = "^0.14.0"


[tool.pylint.message_control]
disable = [
    "missing-module-docstring",
]


[tool.poetry-dynamic-versioning]
enable = true


[build-system]
requires = ["poetry>=1.0.2", "poetry-dynamic-versioning"]
build-backend = "poetry.masonry.api"
